language: python

python:
  - '3.6'

addons:
  chrome: stable

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - install-webdrivers

env:
  - SECRET_KEY="7q+i=7c%v)-bwudx&^+p7ltj@c30he1&@i9ggfd3ls26r!isim"

services:
  - postgresql

script:
  - cd openrider && python manage.py test -v2