language: python

python:
  - '3.6'

addons:
  chrome: stable

install:
  - pip install pipenv
  - pipenv install --dev

env: DJANGO_SETTINGS_MODULE="openrider.settings"

services:
  - postgresql

script:
  - cd openrider && python manage.py test -v2
