language: python

python:
  - '3.6'

addons:
  chrome: stable

branches:
  only: master

install:
  - pip installe pipenv
  - pipenv install --dev

before_script:
  - install-webdrivers

env: DJANGO_SETTINGS_MODULE="openrider.settings"

services:
  - postgresql

script:
  - cd openrider && python manage.py test -v2
