# Generated by Django 3.0.8 on 2020-07-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('road', models.CharField(max_length=250)),
                ('zipcode', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.Category')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.Parking')),
            ],
        ),
    ]
