# Generated by Django 3.0.8 on 2020-07-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAccomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addAccomodation_name', models.CharField(max_length=128, verbose_name='Nom')),
                ('addAccomodation_category', models.CharField(choices=[('hotel', 'Hotel'), ('gite', 'Gite'), ('bnb', 'BnB')], max_length=16, verbose_name='Catégorie')),
                ('addAccomodation_number', models.PositiveSmallIntegerField(verbose_name='Numéro')),
                ('addAccomodation_road', models.CharField(max_length=248, verbose_name='Adresse')),
                ('addAccomodation_zipcode', models.PositiveIntegerField(verbose_name='Code Postal')),
                ('addAccomodation_city', models.CharField(max_length=50, verbose_name='Ville')),
                ('addAccomodation_phone', models.BigIntegerField(verbose_name='Téléphone')),
                ('addAccomodation_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('addAccomodation_url', models.URLField(verbose_name='URL')),
                ('addAccomodation_parking', models.CharField(choices=[('garage', 'Garage'), ('couvert', 'Couvert'), ('ferme', 'Fermé')], max_length=16, verbose_name='Type de parking')),
                ('addAccomodation_statut', models.CharField(choices=[('Non_lu', 'Non lu'), ('Lu', 'Lu'), ('Archive', 'Archivé')], default='Non_lu', max_length=16, verbose_name='Statut de la demande')),
            ],
        ),
    ]
