# Generated by Django 3.0.8 on 2020-08-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addaccomodation',
            name='addAccomodation_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Numéro'),
        ),
    ]
