# Generated by Django 3.1 on 2020-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaccomodation',
            name='addAccomodation_image',
            field=models.ImageField(blank=True, null=True, upload_to='accomodation/'),
        ),
    ]
