# Generated by Django 3.1 on 2020-09-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodation',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='addaccomodation',
            name='addAccomodation_image',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='addaccomodation',
            name='addAccomodation_image1',
            field=models.ImageField(blank=True, default='default_accomodation_image.jpg', null=True, upload_to='accomodation/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='addaccomodation',
            name='addAccomodation_image2',
            field=models.ImageField(blank=True, null=True, upload_to='accomodation/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='addaccomodation',
            name='addAccomodation_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.category', verbose_name="Categorie d'hébergement"),
        ),
        migrations.AlterField(
            model_name='addaccomodation',
            name='addAccomodation_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='addaccomodation',
            name='addAccomodation_parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.parking', verbose_name='Type de Parking'),
        ),
    ]
