# Generated by Django 3.0.8 on 2020-08-05 10:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0002_auto_20200804_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=7), blank=True, null=True, size=None),
        ),
    ]
