# Generated by Django 3.1 on 2020-08-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0002_addaccomodation_addaccomodation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accomodation_checked', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='addaccomodation',
            name='addAccomodation_image',
            field=models.ImageField(blank=True, null=True, upload_to='accomodation/', verbose_name='Image'),
        ),
    ]
