# Generated by Django 3.1 on 2020-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0002_auto_20200910_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodation',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='addaccomodation',
            name='addAccomodation_image1',
        ),
        migrations.RemoveField(
            model_name='addaccomodation',
            name='addAccomodation_image2',
        ),
        migrations.AddField(
            model_name='addaccomodation',
            name='addAccomodation_image',
            field=models.ImageField(blank=True, default='default_accomodation_image.jpg', null=True, upload_to='accomodation/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='addaccomodation',
            name='addAccomodation_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
