# Generated by Django 3.0.8 on 2020-08-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0002_auto_20200811_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='lat',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='lon',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
