# Generated by Django 3.1 on 2020-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0004_auto_20200820_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
