# Generated by Django 3.1 on 2020-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0005_auto_20200821_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addaccomodation',
            name='addAccomodation_image',
            field=models.ImageField(blank=True, default='default_accomodation_image.jpg', null=True, upload_to='accomodation/', verbose_name='Image'),
        ),
    ]
