# Generated by Django 3.1 on 2020-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0006_auto_20200821_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
    ]
