# Generated by Django 3.1 on 2020-08-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0007_auto_20200821_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
    ]
