# Generated by Django 3.1 on 2020-08-26 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accomodation', '0008_auto_20200821_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
